### ISSUE TITLE
Question about consuming

### ISSUE THREAD

**Issue by hbanzon** [gciatto/kt-npm-publish#2]
I'm unable to access this plugin from my project when I try to consume:

```
plugins {
    kotlin("multiplatform") version "1.5.20"
    id("maven-publish")
    id("com.jfrog.artifactory") version "4.21.0"
    id("kt-npm-publish") version "0.3.9"
}
```

Do I need to load it to project locally?

**Comment by gciatto** [comment]
Yes.

If you only write that in your `rootProject`, the plugin will only be applied to the `rootProject`.

To apply the plugin to all projects at once -- provided that these are all either JS projects or MP projects --, you may try writing into the `rootProject`'s `build.gradle(.kts)` file:
```kotlin
import io.github.gciatto.kt.node.NpmPublishPlugin

allprojects {
    apply<NpmPublishPlugin>()
}
```
